# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_guis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets, QtGui
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication, QLabel,QFileDialog,QScrollArea,QWidget,QVBoxLayout

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(935, 662)
        self.Exit = QtWidgets.QPushButton(Dialog)
        self.Exit.setGeometry(QtCore.QRect(20, 590, 421, 51))
        self.Exit.setObjectName("Exit")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(470, 620, 441, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(30, 460, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.reset = QtWidgets.QPushButton(Dialog)
        self.reset.setGeometry(QtCore.QRect(20, 80, 131, 51))
        self.reset.setObjectName("reset")
        self.session = QtWidgets.QPushButton(Dialog)
        self.session.setGeometry(QtCore.QRect(160, 80, 131, 51))
        self.session.setObjectName("session")
        self.logoff = QtWidgets.QPushButton(Dialog)
        self.logoff.setGeometry(QtCore.QRect(20, 180, 131, 51))
        self.logoff.setObjectName("logoff")
        self.tasklist = QtWidgets.QPushButton(Dialog)
        self.tasklist.setGeometry(QtCore.QRect(300, 80, 131, 51))
        self.tasklist.setObjectName("tasklist")
        self.taskkill = QtWidgets.QPushButton(Dialog)
        self.taskkill.setGeometry(QtCore.QRect(20, 260, 131, 51))
        self.taskkill.setObjectName("taskkill")
        self.send_file_input = QtWidgets.QPushButton(Dialog)
        self.send_file_input.setGeometry(QtCore.QRect(20, 350, 421, 51))
        self.send_file_input.setObjectName("send_file_input")
        self.id_session = QtWidgets.QLineEdit(Dialog)
        self.id_session.setGeometry(QtCore.QRect(170, 200, 261, 31))
        self.id_session.setObjectName("id_session")
        self.taskkill_pid = QtWidgets.QLineEdit(Dialog)
        self.taskkill_pid.setGeometry(QtCore.QRect(170, 280, 261, 31))
        self.taskkill_pid.setObjectName("taskkill_pid")
        self.hostname = QtWidgets.QLineEdit(Dialog)
        self.hostname.setGeometry(QtCore.QRect(20, 40, 411, 31))
        self.hostname.setObjectName("hostname")
        self.display = QtWidgets.QLabel(Dialog)
        self.display.setGeometry(QtCore.QRect(470, 20, 421, 581))
        self.display.setText("")
        self.display.setObjectName("display")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 411, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(170, 180, 211, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(170, 260, 261, 16))
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 150, 411, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(20, 330, 411, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.route_label = QtWidgets.QLabel(Dialog)
        self.route_label.setGeometry(QtCore.QRect(20, 410, 421, 31))
        self.route_label.setText("")
        self.route_label.setObjectName("route_label")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(470, 40, 441, 551))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Menu de Soporte y MDA"))
        self.Exit.setText(_translate("Dialog", "Exit"))
        self.reset.setText(_translate("Dialog", "Reiniciar Equipo"))
        self.session.setText(_translate("Dialog", "Checkear sesiones"))
        self.logoff.setText(_translate("Dialog", "Cerrar sesion"))
        self.tasklist.setText(_translate("Dialog", "Mostrar procesos"))
        self.taskkill.setText(_translate("Dialog", "Cerrar proceso"))
        self.send_file_input.setText(_translate("Dialog", "Enviar archivo"))
        self.label_2.setText(_translate("Dialog", "Nombre de equipo |  Hostname"))
        self.label_3.setText(_translate("Dialog", "ID de sesión  |  Session ID"))
        self.label_4.setText(_translate("Dialog", "PID del proceso  |  PID process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
